version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark Master port
    environment:
      - SPARK_MODE=master
    volumes:
      - C:\Users\renu4\MachineLearning\MCA_RankList_Analysis:/opt/spark-scripts 

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
